language: node_js

node_js:
  - 4.0
  - 4
  - 5

install:
  - mkdir /dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /dynamodb

sudo: false